# Generated by Django 2.1.1 on 2018-09-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('truck_model', models.CharField(max_length=20)),
                ('max_weight', models.IntegerField(default=0)),
                ('current_weight', models.IntegerField(default=0)),
            ],
        ),
    ]
